global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['192.168.68.55:9182']
